version: "3"

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    container_name: postgres-moto
    environment:
      POSTGRES_DB: moto_db
      # You should definitely change the password in production
      POSTGRES_PASSWORD: enki
      POSTGRES_USER: enki
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - webdev
  ###< doctrine/doctrine-bundle ###
  pgadmin:
    container_name: pgadmin4-moto
    image: dpage/pgadmin4
    depends_on:
      - database
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: enki@enki.com
      PGADMIN_DEFAULT_PASSWORD: enki
    ports:
      - "5051:80"
    networks:
      - webdev
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq-moto
    ports: [5672, 15672]
    restart: always
    networks:
      - webdev
  portainer-ce:
    image: portainer/portainer-ce
    container_name: "portainer-moto"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webdev

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
networks:
  webdev:
